/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Excepcion.DatoInvalidoExcepcion;
import controlador.PagoControlador;
import dto.PagoDTO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 *
 * @author PEDRO LUIS MARTINEZ
 */




public class FormPago extends JFrame {

    private JTextField txtIdConsulta, txtIdPropietario, txtMonto;
    private DefaultTableModel modeloTabla;
    private JTable tablaPagos;
    private final PagoControlador controlador = new PagoControlador();

    public FormPago() {
        setTitle("Gestión de Pagos");
        setSize(800, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        // Panel superior: formulario
        JPanel panelFormulario = new JPanel(new GridLayout(4, 2, 10, 10));
        panelFormulario.setBorder(BorderFactory.createTitledBorder("Registrar Pago"));

        txtIdConsulta = new JTextField();
        txtIdPropietario = new JTextField();
        txtMonto = new JTextField();

        panelFormulario.add(new JLabel("ID Consulta:"));
        panelFormulario.add(txtIdConsulta);
        panelFormulario.add(new JLabel("ID Propietario:"));
        panelFormulario.add(txtIdPropietario);
        panelFormulario.add(new JLabel("Monto:"));
        panelFormulario.add(txtMonto);

        JButton btnRegistrar = new JButton("Registrar Pago");
        btnRegistrar.addActionListener(e -> registrarPago());
        panelFormulario.add(btnRegistrar);

        JButton btnVolver = new JButton("Volver al Menú");
        btnVolver.addActionListener(e -> {
            dispose();
            new MenuPrincipal().setVisible(true);
        });
        panelFormulario.add(btnVolver);

        add(panelFormulario, BorderLayout.NORTH);

        // Tabla de pagos
        modeloTabla = new DefaultTableModel(new Object[]{"ID Pago", "Consulta", "Propietario", "Monto", "Fecha"}, 0);
        tablaPagos = new JTable(modeloTabla);
        JScrollPane scroll = new JScrollPane(tablaPagos);
        scroll.setBorder(BorderFactory.createTitledBorder("Pagos Registrados"));
        add(scroll, BorderLayout.CENTER);
        cargarPagos();
    }

    private void registrarPago() {
        try {
            String idConsulta = txtIdConsulta.getText().trim();
            String idPropietario = txtIdPropietario.getText().trim();
            double monto = Double.parseDouble(txtMonto.getText().trim());

            controlador.registrarPago(idConsulta, idPropietario, monto);

            JOptionPane.showMessageDialog(this, "Pago registrado correctamente.");
            limpiarCampos();
            cargarPagos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El monto debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (DatoInvalidoExcepcion e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Validación", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void cargarPagos() {
        modeloTabla.setRowCount(0);
        List<PagoDTO> pagos = controlador.listarPagos();
        for (PagoDTO p : pagos) {
            modeloTabla.addRow(new Object[]{
                    p.getIdPago(),
                    p.getIdConsulta(),
                    p.getIdPropietario(),
                    p.getMonto(),
                    p.getFecha()
            });
        }
    }

    private void limpiarCampos() {
        txtIdConsulta.setText("");
        txtIdPropietario.setText("");
        txtMonto.setText("");
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
