/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.ConsultaVeterinariaControlador;
import transferencia.ConsultaVeterinariaDTO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;
import vista.MenuPrincipal;
/**
 *
 * @author PEDRO LUIS MARTINEZ
 */


public class FormReporteConsultasMascota extends JFrame {

    private JTextField txtIdMascota;
    private JTable tabla;
    private DefaultTableModel modelo;
    private final ConsultaVeterinariaControlador controlador = new ConsultaVeterinariaControlador();

    public FormReporteConsultasMascota() {
        setTitle("Reporte: Consultas por Mascota");
        setSize(800, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        JPanel panelSuperior = new JPanel();
        panelSuperior.add(new JLabel("ID de Mascota:"));
        txtIdMascota = new JTextField(10);
        panelSuperior.add(txtIdMascota);
        JButton btnBuscar = new JButton("Generar Reporte");
        btnBuscar.addActionListener(e -> generarReporte());
        panelSuperior.add(btnBuscar);
        add(panelSuperior, BorderLayout.NORTH);

        modelo = new DefaultTableModel(new Object[]{"ID Consulta", "Fecha", "Veterinario", "Motivo", "Diagnóstico", "Tratamiento"}, 0);
        tabla = new JTable(modelo);
        add(new JScrollPane(tabla), BorderLayout.CENTER);

        JButton btnVolver = new JButton("Volver al Menú");
        btnVolver.addActionListener(e -> {
            dispose();
            new MenuPrincipal().setVisible(true);
        });
        JPanel panelInferior = new JPanel();
        panelInferior.add(btnVolver);
        add(panelInferior, BorderLayout.SOUTH);
    }

    private void generarReporte() {
        String idMascota = txtIdMascota.getText().trim();
        if (idMascota.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa el ID de la mascota.");
            return;
        }

        List<ConsultaVeterinariaDTO> consultas = controlador.listarPorMascota(idMascota);
        modelo.setRowCount(0);

        if (consultas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron consultas para esa mascota.");
            return;
        }

        for (ConsultaVeterinariaDTO c : consultas) {
            modelo.addRow(new Object[]{
                c.getIdConsulta(),
                c.getFecha(),
                c.getIdVeterinario(),
                c.getMotivo(),
                c.getDiagnostico(),
                c.getTratamiento()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReporteConsultasMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReporteConsultasMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReporteConsultasMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReporteConsultasMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReporteConsultasMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
