/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author PEDRO LUIS MARTINEZ
 */

import javax.swing.*;
import utils.Estilo;
import vista.FormMascota;

public class MenuPrincipal extends JFrame {

    public MenuPrincipal() {
        setTitle("Sistema Veterinario - Menú Principal");
        setSize(600, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        Estilo.aplicarEstiloVentana(this);

        initUI();
    }

    private void initUI() {
        JMenuBar barra = new JMenuBar();
        JMenu menuGestion = new JMenu("Gestión");
        JMenu menuHistorial = new JMenu("Historial");
        
        Estilo.aplicarEstiloVentana(this);

        JMenuItem itemHistorial = new JMenuItem("Historial 🐾");
        itemHistorial.addActionListener(e -> {
            FormHistorialClinico form = new FormHistorialClinico();
            form.setVisible(true);
        });
        
        JMenuItem itemConsulta = new JMenuItem("Consulta");
        itemConsulta.addActionListener(e -> {
            FormConsultaVeterinaria form = new FormConsultaVeterinaria();
            form.setVisible(true);
            dispose(); // Cierra el menú
        });
        
        JMenuItem itemReporte = new JMenuItem("Reporte");
        itemReporte.addActionListener(e -> {
            new FormReporteConsultasMascota().setVisible(true);
            dispose();
        });
      
        JMenuItem itemSalir = new JMenuItem("Salir");
        itemSalir.addActionListener(e -> {
            dispose();
        });

        JMenuItem itemPagos = new JMenuItem("Pagos");
        itemPagos.addActionListener(e -> {
            new FormPago().setVisible(true);
            dispose();
        });
        
        JMenuItem itemMascotas = new JMenuItem("Mascotas 🐾");
        itemMascotas.addActionListener(e -> {
            FormMascota form = new FormMascota();
            form.setVisible(true);
        });
       
      

        JMenuItem itemPropietarios = new JMenuItem("Propietarios 🧑‍🌾");
        itemPropietarios.addActionListener(e -> {
            FormPropietario form = new FormPropietario();
            form.setVisible(true);
        });

        JMenuItem itemVeterinarios = new JMenuItem("Veterinarios 👨‍⚕️");
        itemVeterinarios.addActionListener(e -> {
            FormVeterinario form = new FormVeterinario();
            form.setVisible(true);
        });

        menuGestion.add(itemMascotas);
        menuGestion.add(itemPropietarios);
        menuGestion.add(itemVeterinarios);
        menuHistorial.add(itemHistorial);
        
        
        
        barra.add(menuGestion);
        barra.add(menuHistorial);
        barra.add(itemConsulta);
        barra.add(itemReporte);
        barra.add(itemPagos);
        barra.add(itemSalir);
        
        setJMenuBar(barra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
